# Generated by Django 5.1.6 on 2025-03-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspacemember_invited_at_workspacemember_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemember',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspaces.workspace'),
        ),
    ]
