# Generated by Django 5.1.6 on 2025-03-06 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('color', models.CharField(default='#FFFFFF', help_text='Hex color (e.g. #FF5733)', max_length=7)),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
            },
        ),
        migrations.CreateModel(
            name='CardLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='cards.card')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='labels.label')),
            ],
        ),
    ]
