# Generated by Django 5.1.6 on 2025-03-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='TaskList',
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(default='#FFFFFF', help_text='Hex color (e.g. #FF5733)', max_length=7),
        ),
    ]
