# Generated by Django 5.1.6 on 2025-03-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_rename_list_tasklist_alter_label_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'verbose_name': 'TaskList', 'verbose_name_plural': 'TaskLists'},
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='colour',
        ),
    ]
